apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe
  labels:
    app: tic-tac-toe
spec:
  type: LoadBalancer
  ports:
  - port: 90
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: tic-tac-toe
